cray-hdf5-parallel(3):ERROR:105: Unable to locate a modulefile for 'cray-hdf5-parallel/1.10.2.0'
Warning: Python module not loaded, you already have Python loaded via conda init
ModuleCmd_Load.c(244):ERROR:105: Unable to locate a modulefile for 'h5py-parallel/2.9.0'
/opt/cray/pe/modules/3.2.11.4/bin/modulecmd: error while loading shared libraries: libtcl8.6.so: cannot open shared object file: No such file or directory
/opt/cray/pe/modules/3.2.11.4/bin/modulecmd: error while loading shared libraries: libtcl8.6.so: cannot open shared object file: No such file or directory
/opt/cray/pe/modules/3.2.11.4/bin/modulecmd: error while loading shared libraries: libtcl8.6.so: cannot open shared object file: No such file or directory
/opt/cray/pe/modules/3.2.11.4/bin/modulecmd: error while loading shared libraries: libtcl8.6.so: cannot open shared object file: No such file or directory
ls: cannot access 'mechs/*.inc': No such file or directory
/global/homes/m/mikelam/.bashrc: line 10: module: command not found
/global/homes/m/mikelam/.bashrc: line 11: module: command not found
/global/homes/m/mikelam/.bashrc: line 12: module: command not found
/global/homes/m/mikelam/.bashrc: line 13: module: command not found
/global/homes/m/mikelam/.bashrc: line 10: module: command not found
/global/homes/m/mikelam/.bashrc: line 11: module: command not found
/global/homes/m/mikelam/.bashrc: line 12: module: command not found
/global/homes/m/mikelam/.bashrc: line 13: module: command not found
/global/homes/m/mikelam/.bashrc: line 10: module: command not found
/global/homes/m/mikelam/.bashrc: line 11: module: command not found
/global/homes/m/mikelam/.bashrc: line 12: module: command not found
/global/homes/m/mikelam/.bashrc: line 13: module: command not found
/global/homes/m/mikelam/.bashrc: line 10: module: command not found
/global/homes/m/mikelam/.bashrc: line 11: module: command not found
/global/homes/m/mikelam/.bashrc: line 12: module: command not found
/global/homes/m/mikelam/.bashrc: line 13: module: command not found
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
Traceback (most recent call last):
  File "/global/u1/m/mikelam/SimulatingVariants/Optimization_HHtoHMM.py", line 23, in <module>
    old_update = algo._update_history_and_hof
AttributeError: module 'bluepyopt.deapext.algorithms' has no attribute '_update_history_and_hof'
srun: error: nid01388: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=56217372.0
