Warning: Python module not loaded, you already have Python loaded via conda init
/usr/bin/shifter: ./drive.sh: No such file or directory
srun: error: nid00808: task 0: Exited with exit code 127
srun: launch/slurm: _step_signal: Terminating StepId=52730297.0
chmod: missing operand after ‘a+x’
Try 'chmod --help' for more information.
/var/spool/slurmd/job52730297/slurm_script: line 20: drive.sh:: command not found
/global/cscratch1/sd/adisaran/neuronBBP_build2/nrn/lib/python/
/global/u1/m/mikelam/SimulatingVariants
ls: cannot access 'mechs/*.inc': No such file or directory
mechs/na12_mut.mod mechs/na16.mod mechs/na8stmut.mod mechs/vclmp_pl.mod
na12_mut.mod na16.mod na8stmut.mod vclmp_pl.mod
"/global/cscratch1/sd/adisaran/neuronBBP_build2/nrn/share/nrn/libtool" --tag=CC --mode=compile mpicc -DHAVE_CONFIG_H  -I. -I.. -I"/global/cscratch1/sd/adisaran/neuronBBP_build2/nrn/include/nrn" -I"/global/cscratch1/sd/adisaran/neuronBBP_build2/nrn/x86_64/lib"      -g -O2 -c -o mod_func.lo mod_func.c
Warning: Python module not loaded, you already have Python loaded via conda init
libtool: compile:  mpicc -DHAVE_CONFIG_H -I. -I.. -I/global/cscratch1/sd/adisaran/neuronBBP_build2/nrn/include/nrn -I/global/cscratch1/sd/adisaran/neuronBBP_build2/nrn/x86_64/lib -g -O2 -c mod_func.c  -fPIC -DPIC -o .libs/mod_func.o
/global/cscratch1/sd/adisaran/neuronBBP_build2/nrn/share/nrn/libtool: line 1762: mpicc: command not found
make: *** [/global/cscratch1/sd/adisaran/neuronBBP_build2/nrn/x86_64/bin/nrnmech_makefile:88: mod_func.lo] Error 1
Requirement already satisfied: neuron in /global/cscratch1/sd/adisaran/neuronBBP_build2/nrn/lib/python (7.6)
Traceback (most recent call last):
  File "/global/cscratch1/sd/adisaran/neuronBBP_build2/nrn/lib/python/neuron/__init__.py", line 106, in <module>
    import hoc
ModuleNotFoundError: No module named 'hoc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/cscratch1/sd/adisaran/neuronBBP_build2/nrn/lib/python/neuron/__init__.py", line 110, in <module>
    import neuron.hoc
ModuleNotFoundError: No module named 'neuron.hoc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/u1/m/mikelam/SimulatingVariants/Optimization_HHtoHMM.py", line 3, in <module>
    import generalized_genSim_shorten_time_HMM as ggsdHMM
  File "/global/u1/m/mikelam/SimulatingVariants/generalized_genSim_shorten_time_HMM.py", line 11, in <module>
    from neuron import h, gui
  File "/global/cscratch1/sd/adisaran/neuronBBP_build2/nrn/lib/python/neuron/__init__.py", line 112, in <module>
    exec("import neuron.hoc%d%d as hoc" % (sys.version_info[0], sys.version_info[1]))
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'neuron.hoc37'
